### ISSUE TITLE
Select All/None capabilities UI/UX pattern

### ISSUE THREAD

**Issue by skorasaurus** [caseproof/members#54] opened 2021-07-16 17:50 UTC
A 'select all' and select none' UI/UX pattern in the role editor would be appreciated. 

I needed to create a role that nearly all permissions except for a handful; and it was mildly annoying to go through and create a role and clicking dozens of times.

**Comment by cartpauj** [comment] 2024-11-29 21:59
Closing as duplicate ofhttps://github.com/caseproof/members/issues/11

**Closed by cartpauj** 2024-11-29 21:59 UTC
